### ISSUE TITLE
Configuration Cascading (.eslintrc) not working

### ISSUE THREAD

**Issue by pgoldrbx** [idok/eslint-plugin#18]
The ESLint plugin only considers the first `.eslintrc` file that it finds, rather than properly cascading.

running `eslint` from the command-line works as expected.

See: "Configuration Cascading and Hierarchy" in [Configuring ESLint](http://eslint.org/docs/configuring/)

**Preferences:**
```
Languages & Frameworks > JavaScript > Code Quality Tools > ESLint

Configuration file:
[x] Search for suitable .eslintrc
When linting a javascript file, the IDE looks for .eslintrc starting from the file's
folder and then moving up to the filesystem root.
```

**Comment by idok** [comment]
is this still relevant?
