### ISSUE TITLE
add build steps to readme and/or mavenize project

### ISSUE THREAD

**Issue by ispringer** [idok/eslint-plugin#20]
Can you please add the build steps to the readme? It would be great if you could mavenize, but either way.

Also, would you mind doing a release that includes your fix for https://github.com/idok/eslint-plugin/issues/19?

Thanks!
Ian

**Comment by idok** [comment]
Currently, to build the project you need to use this menu:

![screen shot 2014-12-11 at 10 27 35](https://cloud.githubusercontent.com/assets/1866543/5391210/6f17745a-8120-11e4-9bbf-583ba877af5f.png)
