### ISSUE TITLE
Please specify ESLint Package correctly: no such directory

### ISSUE THREAD

**Issue by mlissner** [idok/eslint-plugin#22]
I'm struggling to get this setup. I installed ESLint with:

```sudo npm install -g eslint```

Then I ran `updatedb` and `locate eslint.js`, which output:

```
/usr/local/lib/node_modules/eslint/bin/eslint.js
/usr/local/lib/node_modules/eslint/conf/eslint.json
/usr/local/lib/node_modules/eslint/lib/eslint.js
/usr/local/lib/node_modules/eslint/node_modules/doctrine/eslint.json
```

I tried using the first and third result for the ESLint package, but regardless of what I use, Intellij is giving me a message that:

> Please specify ESLint package correctly: no such directory

I've checked and double checked that the files exist and that the correct user can access them. Am I missing something or is this a valid bug?

I'm not deep in the grunt/node/npm world, so I suspect this is my issue, but that others will have it too.

Great project though. Looking forward to using it.

**Comment by idok** [comment]
Hi,
This is probably due to the sudo command, I strongly encourage you not to do package management with sudo, see here:
http://howtonode.org/introduction-to-npm

**Comment by scharf** [comment]
I have the same problem and this is not a problem of `sudo`. Is there a way to figure out why it cannot find the ESLint package?

**Comment by scharf** [comment]
I figured it out: the "ESLint package" is not the path to the `eslint.js` file as suggested in the screenshot [doc/config.png](../blob/master/doc/config.png), but it is the **path** to the package e.g. `/usr/local/lib/node_modules/eslint`.

**Comment by mlissner** [comment]
:+1:

**Comment by ivanoats** [comment]
BTW, if you use NVM, your path will be something like: `~/.nvm/versions/node/v5.6.0/lib/node_modules/eslint`

**Comment by keyurpatel** [comment]
@scharf : +1

**Comment by stevematdavies** [comment]
I point it to my local node modules version of eslint, and it still gives the same errir
