### ISSUE TITLE
NullPointerExceptions when enabling the plugin in Default Settings

### ISSUE THREAD

**Issue by loloakira** [idok/eslint-plugin#23]
On Webstorm 9.0.3, when i try to enable and configure the eslint plugin in the default Settings part, i've got a "NullPointerException : null" Error. 
It's possible to reproduce just going into the "Default Settings" panel, in "Other Settings", select the ESLint Plugin menu and enable the plugin. Then, select the Node interpreter. It always throws the exception.

Detail of the error :

>null
>java.lang.NullPointerException
>	at com.eslint.settings.ESLintSettingsPage.validatePath(ESLintSettingsPage.java:203)
>	at com.eslint.settings.ESLintSettingsPage.validateField(ESLintSettingsPage.java:143)
>	at com.eslint.settings.ESLintSettingsPage.validate(ESLintSettingsPage.java:155)
>	at com.eslint.settings.ESLintSettingsPage.update(ESLintSettingsPage.java:123)
>	at com.eslint.settings.ESLintSettingsPage.access$300(ESLintSettingsPage.java:40)
>	at com.eslint.settings.ESLintSettingsPage$4.run(ESLintSettingsPage.java:116)
>	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2108)
>	at com.eslint.settings.ESLintSettingsPage.updateLaterInEDT(ESLintSettingsPage.java:114)
>	at com.eslint.settings.ESLintSettingsPage.access$200(ESLintSettingsPage.java:40)
>	at com.eslint.settings.ESLintSettingsPage$3.textChanged(ESLintSettingsPage.java:99)
>	at com.intellij.ui.DocumentAdapter.insertUpdate(DocumentAdapter.java:27)
>	at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
>	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
>	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
>	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
>	at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
>	at javax.swing.text.JTextComponent.setText(JTextComponent.java:1669)
>	at javax.swing.plaf.basic.BasicComboBoxEditor$BorderlessTextField.setText(BasicComboBoxEditor.java:144)
>	at javax.swing.plaf.basic.BasicComboBoxEditor.setItem(BasicComboBoxEditor.java:87)
>	at com.intellij.openapi.ui.ComboBox$MyEditor.setItem(ComboBox.java:366)
>	at javax.swing.JComboBox.configureEditor(JComboBox.java:1404)
>	at javax.swing.plaf.basic.BasicComboBoxUI$Handler.contentsChanged(BasicComboBoxUI.java:1864)
>	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
>	at com.intellij.ui.TextFieldWithHistory$MyModel.fireContentsChanged(TextFieldWithHistory.java:157)
>	at com.intellij.ui.TextFieldWithHistory$MyModel.setSelectedItem(TextFieldWithHistory.java:153)
>	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:576)
>	at javax.swing.JComboBox.setSelectedIndex(JComboBox.java:622)
>	at javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:834)
>	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
>	at java.awt.Component.processMouseEvent(Component.java:6525)
>	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
>	at javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:498)
>	at java.awt.Component.processEvent(Component.java:6290)
>	at java.awt.Container.processEvent(Container.java:2234)
>	at java.awt.Component.dispatchEventImpl(Component.java:4881)
>	at java.awt.Container.dispatchEventImpl(Container.java:2292)
>	at java.awt.Component.dispatchEvent(Component.java:4703)
>	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
>	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
>	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
>	at java.awt.Container.dispatchEventImpl(Container.java:2278)
>	at java.awt.Window.dispatchEventImpl(Window.java:2750)
>	at java.awt.Component.dispatchEvent(Component.java:4703)
>	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
>	at java.awt.EventQueue.access$500(EventQueue.java:97)
>	at java.awt.EventQueue$3.run(EventQueue.java:702)
>	at java.awt.EventQueue$3.run(EventQueue.java:696)
>	at java.security.AccessController.doPrivileged(Native Method)
>	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
>	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
>	at java.awt.EventQueue$4.run(EventQueue.java:724)
>	at java.awt.EventQueue$4.run(EventQueue.java:722)
>	at java.security.AccessController.doPrivileged(Native Method)
>	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
>	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
>	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
>	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
>	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
>	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
>	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
>	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
>	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
>	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
>	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
>	at java.security.AccessController.doPrivileged(Native Method)
>	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
>	at java.awt.Dialog.show(Dialog.java:1084)
>	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:779)
>	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:464)
>	at com.intellij.openapi.ui.DialogWrapper.showAndGetOk(DialogWrapper.java:1569)
>	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1536)
>	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:112)
>	at com.intellij.ide.actions.TemplateProjectPropertiesAction.actionPerformed(TemplateProjectPropertiesAction.java:28)
>	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:164)
>	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:266)
>	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:926)
>	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
>	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:236)
>	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
>	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:105)
>	at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:512)
>	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
>	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
>	at java.awt.Component.processMouseEvent(Component.java:6525)
>	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
>	at java.awt.Component.processEvent(Component.java:6290)
>	at java.awt.Container.processEvent(Container.java:2234)
>	at java.awt.Component.dispatchEventImpl(Component.java:4881)
>	at java.awt.Container.dispatchEventImpl(Container.java:2292)
>	at java.awt.Component.dispatchEvent(Component.java:4703)
>	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
>	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
>	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
>	at java.awt.Container.dispatchEventImpl(Container.java:2278)
>	at java.awt.Window.dispatchEventImpl(Window.java:2750)
>	at java.awt.Component.dispatchEvent(Component.java:4703)
>	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
>	at java.awt.EventQueue.access$500(EventQueue.java:97)
>	at java.awt.EventQueue$3.run(EventQueue.java:702)
>	at java.awt.EventQueue$3.run(EventQueue.java:696)
>	at java.security.AccessController.doPrivileged(Native Method)
>	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
>	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
>	at java.awt.EventQueue$4.run(EventQueue.java:724)
>	at java.awt.EventQueue$4.run(EventQueue.java:722)
>	at java.security.AccessController.doPrivileged(Native Method)
>	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
>	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
>	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
>	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:573)
>	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
>	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
>	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
>	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
>	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
>	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by michahell** [comment]
Im getting a null pointer error too, and it even caused my project config to be corrupted. That is really bad , this should never happen in an Editor: plugins should fail silently and notify the user. another reason (for me) not to like WebStorm, seems like a design flaw on their side.
