### ISSUE TITLE
JSON validation issue in WebStorm 10 EAP

### ISSUE THREAD

**Issue by kevinSuttle** [idok/eslint-plugin#24]
I'm sure this isn't a priority, as it's just now an EAP, but WS 10 shows an error.
See: https://github.com/eslint/eslint/issues/667#issuecomment-77408530

**Comment by olore** [comment]
per @nzakas on https://github.com/eslint/eslint/issues/667#issuecomment-77438221 - "We don't plan on having a JSON linter built in because the rules are too different."
