### ISSUE TITLE
Documentation for the ESLInt Package field

### ISSUE THREAD

**Issue by scharf** [idok/eslint-plugin#25]
The reason why some users get the error `Please specify ESLint Package correctly: no such directory`(#22) is that the documentation is wrong. The documentation should state that the field should contain the **path** to the eslint installation and not the path to the eslint.js file.

The screenshot in the docu should look like:

![config](https://cloud.githubusercontent.com/assets/3731059/6711221/fa5cd3be-cd85-11e4-961c-d4d50a30e67e.png)

**Comment by idok** [comment]
As of intellij 14 / webstorm 9, ESLint is part of the platform.
This is not The settings screen of ESLint plugin.
Therefore ESLint plugin documentation doesn't apply.

**Comment by scharf** [comment]
oh! I did not realize that there are two ESLint integrations....
