### ISSUE TITLE
"max-len" problems are not shown

### ISSUE THREAD

**Issue by mickaeltr** [idok/eslint-plugin#27]
Hello,

I have the following rule in my .eslintrc file: `"max-len": [2, 120, 2]`

When running eslint from the command line, I see errors like:
> error  Line 47 exceeds the maximum line length of 120  max-len

However, these issues are not shown in the IntelliJ IDEA UI, with the eslint-plugin.

Cheers

**Comment by idok** [comment]
Can you help me reproduce? looks ok here:
![Uploading Screen Shot 2015-10-01 at 16.25.29.png…]()

**Comment by mickaeltr** [comment]
Hello,
For some reason I don't have this problem anymore.
Thanks
