### ISSUE TITLE
"no-multiple-empty-lines" issues at end-of-file are not shown

### ISSUE THREAD

**Issue by mickaeltr** [idok/eslint-plugin#28]
Hello,

I have the following rule in my .eslintrc file: `"no-multiple-empty-lines": [2, {"max": 1}]`

When running eslint from the command line, I see errors like:
> error  Multiple blank lines not allowed                no-multiple-empty-lines

However, these issues are not shown in the IntelliJ IDEA UI, with the eslint-plugin, when the issue is at the end-of-file. It works otherwise (when the issue is before the end-of-file) though.

Cheers

**Comment by idok** [comment]
Since the errors are marked by a squiggly red underline by default, if the line has no content, it is not visible.
You can, however, see in the right gutter, change the marking settings or check the 'Treat all eslint issues as warnings' in the settings page.

**Comment by mickaeltr** [comment]
Hello,
Sorry, for some reason I don't have this problem anymore.
Thanks
