### ISSUE TITLE
Don't accept nodejs PATH

### ISSUE THREAD

**Issue by LOQUILLO** [idok/eslint-plugin#29]
Don't accept the default path for Nodejs, and it's in my main PATH.
I see this message: Path to node interpreter is invalid Fix it
My specs is Windows 7 x64 Ultimate
WebStorm 10.0.1
![error_ws](https://cloud.githubusercontent.com/assets/1308190/7014452/a154d7b2-dc8a-11e4-88ec-55ab81185610.png)

**Comment by gniavaj** [comment]
hi idok
i don't know how to talk with you on github, so i leave a message here.
i want to learn how to develop plugin of idea through your project eslint-plugin.
but when i lanuch Run 'eslint-plugin',i get some error.
the error message is com.intellij.lang.javascript.psi not exist,
cculd you tell me where i can download the jar from.
thx

**Comment by idok** [comment]
@gniavaj please contact me via my Jetbrains profile details
http://plugins.jetbrains.com/space/index?pr=&lg=kokoMonkey

**Comment by idok** [comment]
@LOQUILLO you need to specify the eslint.cmd file, which is the executable on windows.

**Comment by LOQUILLO** [comment]
Hi @idok isn't working, hold on error.
