### ISSUE TITLE
Use ESLint remotely

### ISSUE THREAD

**Issue by jampy** [idok/eslint-plugin#31]
Is there a way to use ESLint that is installed on a remote SSH server? Just like the PHP CodeSniffer Inspection works..

The reason is that we're using PHPStorm under Windows and would need to install NodeJS/ESLint just for inspection, whereas for all other tasks (like building, testing) we're using Docker containers.

**Comment by idok** [comment]
I'm not familiar with a way to run it remotely, but installing node and eslint is simple, fast and doesn't consume many resources. Give it a try.
