### ISSUE TITLE
.eslintrc assumes JSON format

### ISSUE THREAD

**Issue by thom-nic** [idok/eslint-plugin#32]
The built-in "Eslint Configuration" file association I think assumes your .eslintrc file is JSON but ESlint also supports YAML.  So when I open the file it looks like this:

<img width="564" alt="screen shot 2015-09-30 at 8 09 47 am" src="https://cloud.githubusercontent.com/assets/95562/10192573/5194bd90-674b-11e5-8a51-4aa1c90493d6.png">
  
I can add a file association for YAML but it complains that it's being reassigned from the "eslint configuration" file type.  Don't know if there's any issue other than that though.

**Comment by idok** [comment]
Since eslint 1.10.0 this file format is deprecated, see [here](http://eslint.org/blog/2015/11/eslint-v1.10.0-released/#configuration-file-formats).
The new format has extension and will be supported by intellij by default.

**Comment by thom-nic** [comment]
Ah I see.  Thanks for pointing me to the eslint update!
