### ISSUE TITLE
Configure to work with JSX files

### ISSUE THREAD

**Issue by pburrows** [idok/eslint-plugin#34]
How do I get the ESLint plugin to work with JSX files? It is properly highlighting my .js files. But the .jsx files are not getting the same love. Is there a setting somewhere? 

(note: ESLint and my .eslintrc file is setup to check JSX files, and when I run it through my gulp task, the JSX files are checked. But I like the integration of the plugin and would like to get it to work with JSX as well within WebStorm).

Thanks!

**Comment by idok** [comment]
Add extensions field, just set it to .js,.jsx
