### ISSUE TITLE
Pycharm 5.0.1 upgrade breaks ESLint due to lack of yaml

### ISSUE THREAD

**Issue by ilovejs** [idok/eslint-plugin#36]
Plugin Error
Problems found loading plugins:
Plugin "ESLint" was not loaded: required plugin "org.jetbrains.plugins.yaml" not installed.

I'm using Pycharm Pro 
<img width="238" alt="screen shot 2015-11-16 at 9 53 35 am" src="https://cloud.githubusercontent.com/assets/978919/11171582/feb02e44-8c47-11e5-9c3b-953eed7145cf.png">
5.0.1 (latest patch). This upgrade just break the ESLint plugin.

**Comment by snoepkast** [comment]
+1 having the same issue

**Comment by bjz** [comment]
Is there any workaround for this?

**Comment by richarddewit** [comment]
+1

**Comment by maxmalynowsky** [comment]
+1
