### ISSUE TITLE
How this differs from the one provided by IntelliJ Idea?

### ISSUE THREAD

**Issue by villesau** [idok/eslint-plugin#38]
I'm not aware how this differs from the one provided by IntelliJ Idea. I found this when tried to find out why some of the custom rules were not working with the default eslinter. I suggest to add some comparison/explanation how this differs from the bundled eslit -plugin by Jetbrains.

**Comment by musbaig** [comment]
Also, is it a good idea to run the default eslint plugin at the same time as this one?

**Comment by idok** [comment]
Thanks, @musbaig I wouldn't recommend running with both plugins enabled
https://github.com/idok/eslint-plugin/blob/master/README.md#bundled-plugin
