### ISSUE TITLE
Refactoring eslint error

### ISSUE THREAD

**Issue by jaumard** [idok/eslint-plugin#40]
It would be nice if IntelliJ show some solutions for eslint error, for now it just say "Suppress Eslint rules" but for some rules it will be nice to have other choice. 
Here is a few : 
- ESLint: Strings must use singlequote. (quotes) => Transform quotes in simple quote
- ESLint: Extra space after key "engine". (key-spacing) => Remove space
- ESLint: Missing space before value for key "title". (key-spacing) => Add space
- ESLint: Newline required at end of file but not found. (ell-last) => Add newline

And things that would be amazing is a button to automatically apply the corrections to all eslint errors.

Thanks for your good work on this !

**Comment by idok** [comment]
please see
https://github.com/idok/eslint-plugin#bundled-plugin
