### ISSUE TITLE
ESLint plugins support

### ISSUE THREAD

**Issue by gotbahn** [idok/eslint-plugin#46]
Hello, thank you for awesome plugin. I have a question about using plugins with it.

As example I'm using https://www.npmjs.com/package/eslint-plugin-dollar-sign, which is non recognisable by eslint-plugin in phpStorm. Is it possible to configure it somehow?

**Comment by godban** [comment]
Also I mentioned that plugins brake functionality, I have next error

> ESLint plugin: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING at line 2 column 1 path $

my config is

```json
{
  "plugins": [
    "dollar-sign"
  ],
  "rules": {
    "dollar-sign/dollar-sign": [2, "ignoreProperties"]
  }
}
```

**Comment by outdooricon** [comment]
This is quite important. It makes the eslint plugin unusable for me currently. If you use the local eslint package in your project, then it needs to run within npm so that it can use the locally installed config extensions. See https://github.com/walmartlabs/eslint-config-defaults#limitations .
