### ISSUE TITLE
No file refresh after 'ESLint fix'

### ISSUE THREAD

**Issue by godban** [idok/eslint-plugin#47]
One of the most coolest thing in eslint-plugin imo is autoformat. Only thing that I missing is file refresh after format. I'm using phpStorm and after each run I should manually refresh formatted file to see result.

**Comment by prasadsilva** [comment]
I'm using WebStorm and this plugin is great, however not auto refreshing after fix is a rough experience. 

+1 for this feature.

**Comment by godban** [comment]
Yay! Just updated to new version. Works. Thx!
