### ISSUE TITLE
Usage with community edition

### ISSUE THREAD

**Issue by apreg** [idok/eslint-plugin#50]
Does this plugin works with IntelliJ IDEA 2016.1.2 Community Edition?
I was able to install it. I've enabled, configured it but cannot see any warns or errors in editor.

**Comment by chasm** [comment]
As far as I can tell, there is no one home here.

**Comment by idok** [comment]
Hi,
Sorry for the late response.
I'll check and update.

**Comment by apreg** [comment]
No problem. Thank you.

**Comment by idok** [comment]
Since Community Edition doesn't have the JavaScript plugin which is required, ESLint does not support it.
