### ISSUE TITLE
Error running ESLint inspection...is not a valid Win32 application

### ISSUE THREAD

**Issue by felixl-alleninstitute** [idok/eslint-plugin#64]
Using Windows 10 professional, 64 bit.
Running WebStorm 2017.1.4
Using local project install of eslint, v3.19.0

Here's the error that I get:

1:59 PM	ESLint plugin
				Error running ESLint inspection: Cannot run program "C:\projects\aibs-seadragon\node_modules\eslint\bin\eslint.js" (in directory "C:\projects\aibs-seadragon"): CreateProcess error=193, %1 is not a valid Win32 application
				cwd: C:/projects/aibs-seadragon
				command: C:\projects\aibs-seadragon\node_modules\eslint\bin\eslint.js

1:59 PM	ESLint plugin: Cannot run program "C:\projects\aibs-seadragon\node_modules\eslint\bin\eslint.js" (in directory "C:\projects\aibs-seadragon"): CreateProcess error=193, %1 is not a valid Win32 application

**Comment by idok** [comment]
please see the instructions, you need to point to eslint.cmd

**Comment by felixl-alleninstitute** [comment]
Thanks, my bad. Once I corrected that problem, I was able to get eslint plug to work with a local install of the the ESlint npm package.

**Comment by tatsujb** [comment]
@idok what does that even mean? is that in node modules?

**Comment by tatsujb** [comment]
oh it's in node_modules/.bin

I don't know where you saw that being specified. I had to un-exclude node_modules and search for it in WebStorm to find it. 

the guide really needs updating.

**Comment by manuc66** [comment]
Note that it does not work if pointing to `node_modules/.bin/eslint` AND npm config contains:
`shell = "C:\\Program Files\\Git\\bin\\bash.exe"`
