### ISSUE TITLE
how to show result inspection in Intellij Idea?

### ISSUE THREAD

**Issue by szoyaung** [idok/eslint-plugin#72]
the plugin has working,like the pic!
![1](https://user-images.githubusercontent.com/16623273/37328486-56228b7a-26d5-11e8-96f4-8ff1794b55de.png)

but there is no result inspection（maybe it call result list view or window,my english is not good ~）, how can i show it?

additional remarks：my Intellij Idea version is 2017.3

**Comment by szoyaung** [comment]
additional remarks：my  Intellij Idea version is  2017.3

**Comment by idok** [comment]
you need to run the inspection, go to Analyze->Run inspection by name, and select eslint

**Comment by szoyaung** [comment]
@idok 
it works, you taught me a very important point of knowledge at intellig idea,thank you very much!
And another question, can the Intellij Idea own ESlint（at settings ->Languages & Frameworks ->JavaScript -> Code Quality Tools ->ESLint） show the inspection？
